Algoritmo "contar até valor dado pelo usuario"
// Disciplina   : [Linguagem e Lógica de Programação]
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/11/2022
Var
// Seção de Declarações das variáveis 
 contador, valor : inteiro

Inicio
contador <- 1
escreval("contar até:")
leia(valor)

enquanto (contador<=valor) faca
 escreval( contador)
contador<-contador+1

fimenquanto


Fimalgoritmo