Algoritmo "Multiplos de 2 e 3"
// Data atual  : 29/11/2022
//Faça um algoritmo que apresenta os núemros múltiplos de 2 e 3 no
//intervalo de 1 à 100.
Var
   // Seção de Declarações das variáveis
   contador : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto (contador<=100) faca
      se (contador % 2 = 0) e (contador % 3 = 0) entao
         escreval(contador)
      fimse
      contador<-contador+1
   fimenquanto

Fimalgoritmo