Algoritmo "números impares entre 100 e 200"
// Data atual  : 13/12/2022
//Escreva um algoritmo que gera e escreve os números ímpares
//entre 100 e 200
Var
   // Seção de Declarações das variáveis
   cont: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para cont de 100 ate 200 faca
      se (cont mod 2)<> 0 entao
         escreval(cont)
      fimse
   fimpara

Fimalgoritmo