Algoritmo "SOMA DE 5 VALORES "
// Data atual  : 29/11/2022
//Faça um algoritmo que realize a soma de cinco valores "fornecidos"
//pelo usuário

Var
// Seção de Declarações das variáveis 
numero,cont,soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


para cont de 1 ate 5 faca
 escreva("Entre com o valor: ")
 leia(numero)
 soma<-soma+numero
fimpara
escreval("Resultado da soma ->", soma)

Fimalgoritmo